[package]

name = "bitfield"
version = "0.0.5"
authors = ["Lo√Øc Damien <loic.damien@dzamlo.ch>"]
repository = "https://github.com/dzamlo/rust-bitfield"
license = "MIT OR Apache-2.0"
description = "A procedural macro to generate bitfield-like stuct"

[lib]
name = "bitfield"
plugin = true
